# Generated by Django 6.0.1 on 2026-04-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='original_transaction_id',
            field=models.CharField(blank=True, default='', help_text='Apple original transaction ID for IAP tracking', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='revenuecat_app_user_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
