# Generated by Django 6.0.1 on 2026-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oauth_provider",
            field=models.CharField(
                blank=True,
                choices=[("google", "Google"), ("apple", "Apple")],
                help_text="OAuth provider if user signed up via social login",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_uid",
            field=models.CharField(
                blank=True,
                help_text="Unique ID from OAuth provider",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("oauth_provider__isnull", False)),
                fields=("oauth_provider", "oauth_uid"),
                name="unique_oauth_account",
            ),
        ),
    ]
