# Generated by Django 6.0.1 on 2026-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='analytics_pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for analytics dashboard second-factor verification', max_length=128, null=True),
        ),
    ]
