# Generated by Django 6.0.1 on 2026-02-20 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("womens", "Women's Fashion"),
                            ("mens", "Men's Fashion"),
                            ("unisex", "Unisex"),
                            ("shoes", "Shoes"),
                            ("jewelry", "Jewelry"),
                            ("beauty", "Beauty"),
                            ("streetwear", "Streetwear"),
                            ("activewear", "Activewear"),
                            ("bags", "Bags & Accessories"),
                        ],
                        default="unisex",
                        max_length=30,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("cover_image_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "shopify_domain",
                    models.CharField(
                        blank=True,
                        help_text="Shopify store domain, links to ShopifyVendor",
                        max_length=255,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("likes_count", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brands",
                "ordering": ["-likes_count", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-likes_count"], name="brands_likes_c_d77283_idx"
                    ),
                    models.Index(
                        fields=["category", "-likes_count"],
                        name="brands_categor_17b07b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="deals.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "brand_likes",
                "unique_together": {("user", "brand")},
            },
        ),
    ]
