# Generated by Django 6.0.1 on 2026-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0005_storyboard_nullable_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedstoryboard",
            name="snapshot_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 object key e.g. storyboard/abc123.jpg",
                max_length=500,
            ),
        ),
    ]
