# Generated by Django 6.0.1 on 2026-01-30 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mobile_preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("push_enabled", models.BooleanField(default=True)),
                (
                    "push_deals",
                    models.BooleanField(
                        default=True, help_text="New deal notifications"
                    ),
                ),
                (
                    "push_price_alerts",
                    models.BooleanField(default=True, help_text="Price drop alerts"),
                ),
                (
                    "push_weekly_digest",
                    models.BooleanField(default=False, help_text="Weekly summary"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System Default"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("language", models.CharField(default="en", max_length=10)),
                ("default_sort", models.CharField(default="relevance", max_length=20)),
                ("show_sold_items", models.BooleanField(default=False)),
                ("preferred_sources", models.JSONField(blank=True, default=list)),
                ("save_search_history", models.BooleanField(default=True)),
                ("anonymous_analytics", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Preferences",
                "db_table": "mobile_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=10
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier", max_length=255
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, help_text="e.g., iPhone 15 Pro", max_length=255
                    ),
                ),
                ("app_version", models.CharField(blank=True, max_length=20)),
                ("os_version", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_device_tokens",
            },
        ),
        migrations.CreateModel(
            name="MobileSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mobile.devicetoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_sessions",
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_query", models.CharField(max_length=500)),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("product_image", models.URLField(blank=True, max_length=1000)),
                ("product_url", models.URLField(blank=True, max_length=2000)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "lowest_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("expired", "Expired"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("price_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_price_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("favorites", "Saved Deals"),
                            ("searches", "Search History"),
                            ("alerts", "Price Alerts"),
                            ("preferences", "User Preferences"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_token",
                    models.CharField(
                        blank=True,
                        help_text="Opaque cursor for incremental sync",
                        max_length=255,
                    ),
                ),
                ("server_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_sync_states",
            },
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(fields=["token"], name="mobile_devi_token_026c47_idx"),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="mobile_devi_user_id_77a322_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicetoken",
            unique_together={("user", "device_id")},
        ),
        migrations.AddIndex(
            model_name="mobilesession",
            index=models.Index(
                fields=["session_token"], name="mobile_sess_session_9aa8d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mobilesession",
            index=models.Index(
                fields=["user", "is_active"], name="mobile_sess_user_id_06002a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["user", "is_active"], name="mobile_pric_user_id_b134c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(fields=["status"], name="mobile_pric_status_ace057_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="syncstate",
            unique_together={("user", "entity_type")},
        ),
    ]
