# Generated by Django 6.0.1 on 2026-04-03 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("image_search", "Image Search"),
                            ("openai_vision", "OpenAI Vision"),
                            ("remove_bg", "Background Removal"),
                            ("storyboard_upload", "Storyboard Image Upload"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Estimated cost in USD",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_usage_logs",
                "indexes": [
                    models.Index(
                        fields=["user", "endpoint", "created_at"],
                        name="api_usage_l_user_id_710d01_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "endpoint", "created_at"],
                        name="api_usage_l_ip_addr_d55db1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="api_usage_l_created_c81af4_idx"
                    ),
                ],
            },
        ),
    ]
