# Generated by Django 6.0.1 on 2026-04-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0002_add_api_usage_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="default_latitude",
            field=models.FloatField(
                blank=True, help_text="Saved home latitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="default_location_name",
            field=models.CharField(
                blank=True, default="", help_text="e.g. New York, NY", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="default_longitude",
            field=models.FloatField(
                blank=True, help_text="Saved home longitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="max_distance_miles",
            field=models.PositiveIntegerField(
                default=25,
                help_text="Max distance in miles for local marketplace results",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="preferred_gender",
            field=models.CharField(
                blank=True, default="", help_text="men, women, or unisex", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="preferred_sizes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='e.g. ["S", "M", "L"] or ["8", "10"]',
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="preferred_styles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='e.g. ["casual", "streetwear", "modest"]',
            ),
        ),
    ]
