# Generated by Django 6.0.1 on 2026-04-04 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0003_add_location_style_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FashionTimelineEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="The day this outfit was worn")),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "outfit_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"items": [{"title": "...", "image": "...", "source": "..."}], "notes": "..."}',
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. cozy, bold, minimal",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_fashion_timeline",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="mobile_fash_user_id_8555a4_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
