# Generated by Django 6.0.1 on 2026-04-12 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0004_add_fashion_timeline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusagelog",
            name="endpoint",
            field=models.CharField(
                choices=[
                    ("image_search", "Image Search"),
                    ("gemini_vision", "Gemini Vision"),
                    ("openai_vision", "OpenAI Vision"),
                    ("remove_bg", "Background Removal"),
                    ("storyboard_upload", "Storyboard Image Upload"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DealAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="e.g. black leather jacket under $100", max_length=500
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True,
                        help_text="Normalized query for marketplace search (auto-generated)",
                        max_length=500,
                    ),
                ),
                (
                    "reference_image",
                    models.URLField(
                        blank=True,
                        help_text="S3 URL of reference image",
                        max_length=1000,
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("matches_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mobile_deal_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealAlertMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deal_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("deal_data", models.JSONField(default=dict)),
                ("is_seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="mobile.dealalert",
                    ),
                ),
            ],
            options={
                "db_table": "mobile_deal_alert_matches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dealalert",
            index=models.Index(
                fields=["user", "is_active"], name="mobile_deal_user_id_499a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealalert",
            index=models.Index(fields=["status"], name="mobile_deal_status_5ef410_idx"),
        ),
        migrations.AddIndex(
            model_name="dealalertmatch",
            index=models.Index(
                fields=["alert", "is_seen"], name="mobile_deal_alert_i_a1b98e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dealalertmatch",
            unique_together={("alert", "deal_id")},
        ),
    ]
