# Generated by Django 6.0.1 on 2026-02-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Block"),
                            ("brand_showcase", "Brand Showcase"),
                            ("gallery", "Image Gallery"),
                        ],
                        default="brand_showcase",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Section title, e.g. '01. AURALEE'",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Optional subtitle or description",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text content for text sections"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Section",
                "verbose_name_plural": "Content Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "brand",
                    models.CharField(
                        help_text="Brand name, e.g. 'AURALEE'", max_length=100
                    ),
                ),
                (
                    "product_name",
                    models.CharField(help_text="Product name", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Product image", upload_to="blog/products/"
                    ),
                ),
                (
                    "price",
                    models.CharField(help_text="Price, e.g. '$1,200'", max_length=50),
                ),
                (
                    "sale_price",
                    models.CharField(
                        blank=True, help_text="Sale price (optional)", max_length=50
                    ),
                ),
                (
                    "product_url",
                    models.URLField(
                        help_text="Link to product page (affiliate or direct)"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="blog.contentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Card",
                "verbose_name_plural": "Product Cards",
                "ordering": ["order"],
            },
        ),
    ]
