# Generated by Django 6.0.1 on 2026-02-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_add_content_sections_and_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcard",
            name="retailer",
            field=models.CharField(
                blank=True,
                help_text="Retailer name, e.g. 'HARRODS', 'MR PORTER'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productcard",
            name="product_url",
            field=models.URLField(
                blank=True,
                help_text="Optional external link. Leave empty to link to Fynda search.",
            ),
        ),
    ]
